### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by ulises-jimenez** [holtjp/dealcloud-python#3]
Hi there, just wondering if this project is abandoned or not. Feel free to email me at me@ulisesjimenez.com, would love to chat about this @holtjp

**Comment by holtjp** [comment]
I have not abandoned this project. However, I am no longer an employee at DealCloud. So I can't speak to whether this would be the best approach to integrating with their platform. At the time I was leaving the company, they were releasing a preliminary version a REST service. Prior to that, they only offered a .NET-based SOAP service, and interacting it was tricky if you were not coding your client app in a .NET Framework language. I wrote this package to make the WCF service accessible from Python3, and open sourced it with my manager's permission.

I'm happy to answer questions about how this is meant to work. I would point to `examples` folder as a start. If you are a DealCloud customer though, then you should obviously reach out to your account manager/customer success manager with questions and ask for the Technical Services team.

**Comment by ulises-jimenez** [comment]
Hey James, thanks for the reply. The service has been more or less moved to a REST service, but unfortunately it has hardly any documentation. I hope that efforts like these get more support from DealCloud in the future, as ease of integration is a major selling point for many potential customers. Thanks for the help!
